name: Sync Code from Google Drive

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour (adjust as needed)
  workflow_dispatch:  # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download from Google Drive
        run: |
          mkdir -p drive_sync
          cd drive_sync
          curl -L "https://drive.google.com/uc?export=download&id=1fT37Yx40mH1kDZbmfc8IE2yI3Qm9hpMb" -o code.zip
          unzip code.zip
          cd ..
          cp -r drive_sync/* .
          rm -rf drive_sync

      - name: Commit and Push Changes
        run: |
          git config --global user.email "enapster1@example.com"
          git config --global user.name "efatha1"
          git add .
          git commit -m "Synced code from Google Drive" || echo "No changes to commit"
          git push origin main
